FROM rust:1.75-slim-bullseye

RUN apt update && \
    apt install -y --no-install-recommends \
    curl \
    jq \
    libssl-dev \
    pkg-config \
    tini && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fsSL -o /tmp/docker.tgz https://download.docker.com/linux/static/stable/$(uname -m)/docker-24.0.7.tgz && \
    tar -C /tmp -xf /tmp/docker.tgz && \
    mv /tmp/docker/* /usr/bin/ && \
    rm -rf /tmp/docker /tmp/docker.tgz

WORKDIR /app
COPY . .

ENV RUST_BACKTRACE=1

ENTRYPOINT ["tini", "--"]
CMD ["sleep", "infinity"]
